# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aootype', models.CharField(max_length=1)),
                ('expend', models.FloatField(blank=True, null=True)),
                ('income', models.FloatField(blank=True, null=True)),
                ('charity_count', models.IntegerField()),
                ('subsidiary_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aooname', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('expend', models.FloatField(blank=True, null=True)),
                ('income', models.FloatField(blank=True, null=True)),
                ('charity_count', models.IntegerField()),
                ('subsidiary_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LACount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aootype', models.CharField(max_length=1)),
                ('aookey', models.IntegerField()),
                ('aooname', models.CharField(max_length=255)),
                ('expend', models.FloatField(blank=True, null=True)),
                ('income', models.FloatField(blank=True, null=True)),
                ('charity_count', models.IntegerField()),
                ('subsidiary_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LAWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aootype', models.CharField(max_length=1)),
                ('aookey', models.IntegerField()),
                ('aooname', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('expend', models.FloatField(blank=True, null=True)),
                ('income', models.FloatField(blank=True, null=True)),
                ('charity_count', models.IntegerField()),
                ('subsidiary_count', models.IntegerField()),
            ],
        ),
    ]
