# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clouds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacount',
            name='expend',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='areacount',
            name='income',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='areawords',
            name='expend',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='areawords',
            name='income',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lacount',
            name='expend',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lacount',
            name='income',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lawords',
            name='expend',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lawords',
            name='income',
            field=models.FloatField(blank=True),
        ),
    ]
